"""Audit the DENTEX release against what its card says, and write the findings.

    python scripts/audit_dentex.py --data data/dentex/raw --out results/dentex_audit

Evidence standard: every overlap number rests on SHA-256 of the extracted image
bytes (exact copies), or on two independent pixel signals (re-encoded copies, see
`dcai.data.near_duplicates`). Before anything is read, each zip is verified
against the SHA-256 that HuggingFace publishes for it. Nothing in the report is
copied by hand.

DENTEX: Hamamci et al., arXiv:2305.19112, CC-BY-NC-SA 4.0. The report contains
aggregate counts and file names only, no images or annotations.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import statistics as st
import zipfile
from dataclasses import replace
from pathlib import Path

from dcai.data.dentex import COCO_FILES, SUBSETS, TEST_ZIP, TRAIN_ZIP, VAL_ZIP, load_dentex
from dcai.data.near_duplicates import near_duplicates, signatures_for, threshold_table
from dcai.data.schema import InventorySource
from dcai.eval.ratings import check_inventory

# Git-LFS SHA-256 published by HuggingFace for ibrahimhamamci/DENTEX (main), from
# https://huggingface.co/api/datasets/ibrahimhamamci/DENTEX/tree/main/DENTEX
PUBLISHED_SHA256 = {
    TRAIN_ZIP: "18b2a2dbc5a2b10b0cc6a7677c46a382f4709ab8c9c3bb94f57b74e38e11ffd3",
    VAL_ZIP: "6370bb4f1024bd610cde13242a465cb2eff195fc02f56ac22126555e7edc7bc3",
    TEST_ZIP: "ed396d6daa133264ddb0ecdbed3f963868d2a31344ba0fab929a6a1773d82ce2",
}
NAMES = {"quadrant": "(a) quadrant", "enumeration": "(b) enumeration",
         "diagnosis": "(c) diagnosis train", "unlabelled": "unlabelled",
         "validation": "validation", "test": "test"}


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 24), b""):
            h.update(chunk)
    return h.hexdigest()


def table(header: list[str], rows: list[list[object]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    return "\n".join(out + ["| " + " | ".join(map(str, r)) + " |" for r in rows])


def region(tooth: int) -> str:
    return "incisor" if tooth <= 2 else "canine" if tooth == 3 else "premolar" if tooth <= 5 else "molar"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--cache", type=Path, default=Path("data/dentex/cache"))
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args(argv)

    for name, expected in PUBLISHED_SHA256.items():
        got = file_sha256(args.data / name)
        if got != expected:
            raise SystemExit(f"{name}: SHA-256 {got} does not match the published {expected}")

    rel = load_dentex(args.data, index_cache=args.cache / "sha256_index.json")
    index = rel.index
    counts = collections.Counter(e.subset for e in index)
    subs = list(SUBSETS)
    md = ["# DENTEX release audit",
          ("Generated by `scripts/audit_dentex.py` from the HuggingFace release "
          "`ibrahimhamamci/DENTEX`. Each zip was verified against its published SHA-256 "
          "before reading. DENTEX: Hamamci et al., arXiv:2305.19112, CC-BY-NC-SA 4.0. "
          "Counts and file names only.")]

    # --- layout and formats (check 4) --------------------------------------------
    with zipfile.ZipFile(args.data / VAL_ZIP) as zf:
        junk = [i.filename for i in zf.infolist()
                if ".ipynb_checkpoints" in i.filename and not i.is_dir()]
    with zipfile.ZipFile(args.data / TRAIN_ZIP) as zf:
        quad_cats = json.loads(zf.read(COCO_FILES["quadrant"]))["categories"]
        c_json = json.loads(zf.read(COCO_FILES["diagnosis"]))
        b_json = json.loads(zf.read(COCO_FILES["enumeration"]))
    vocab = collections.Counter(f"{lab.code}-{lab.word}" for labs in rel.test_labels.values()
                                for lab in labs)
    md += [
        "## Layout and annotation formats (check 4)",
        table(["subset", "images"], [[NAMES[s], counts[s]] for s in subs]),
        "- Subsets (a), (b), (c)-train: COCO JSON, one file per subset inside "
        "`training_data.zip`.\n"
        "- Validation: images in `validation_data.zip`; labels in a *separate* COCO file, "
        "`validation_triple.json`, at the repository root.\n"
        "- Test: LabelMe JSON, one file per image (`disease/label/test_*.json`); labels "
        f"`code-word-FDI`. Vocabulary: {dict(sorted(vocab.items()))}.\n"
        f"- Junk skipped by the loader: {junk or 'none'}.\n"
        "- Category ids are not positional. Quadrant categories in (a): "
        + ", ".join(f"id {c['id']} = \"{c['name']}\"" for c in quad_cats)
        + ". The loader maps every id through its name.\n"
        "- File names are reused across subsets for different images, and the same image "
        "appears under different names. Identity comes from content (SHA-256).",
    ]

    # --- exact copies (SHA-256) --------------------------------------------------
    members: dict[str, set[str]] = collections.defaultdict(set)
    stored = collections.Counter((e.subset, e.sha256) for e in index)
    subsets_of: dict[str, set[str]] = collections.defaultdict(set)
    for e in index:
        members[e.subset].add(e.sha256)
        subsets_of[e.sha256].add(e.subset)
    within = {s: sum(1 for (sub, _), n in stored.items() if sub == s and n > 1) for s in subs}
    name_of = {(e.subset, e.sha256): e.file_name for e in index}
    shared_c_test = sorted(members["diagnosis"] & members["test"])

    def exact_elsewhere(s: str) -> set[str]:
        return members[s] & set().union(*(members[o] for o in subs if o != s))

    md += [
        "## Exact copies: SHA-256 of image bytes (checks 2 and 3)",
        ("Distinct images in the row subset that also occur, byte for byte, in the column "
        "subset. The diagonal counts images stored more than once *within* a subset."),
        table(["", *(NAMES[s] for s in subs)],
              [[NAMES[r], *(f"({within[r]})" if r == c else len(members[r] & members[c])
                            for c in subs)] for r in subs]),
        f"- **{len(exact_elsewhere('test'))} of {counts['test']} test images** have an exact "
        f"copy elsewhere in the release; **{len(shared_c_test)}** "
        f"{'is' if len(shared_c_test) == 1 else 'are'} in the diagnosis training set itself"
        + (": " + ", ".join(f"`{name_of[('diagnosis', h)]}` = `{name_of[('test', h)]}`"
                            for h in shared_c_test) if shared_c_test else "") + ".",
        (f"- **{len(exact_elsewhere('validation'))} of {counts['validation']} validation "
        "images** have an exact copy elsewhere."),
        (f"- **{len(members['diagnosis'] & members['enumeration'])} of {counts['diagnosis']} "
        "diagnosis-train images** also occur in (b)."),
    ]

    # --- re-encoded copies (pixels) ----------------------------------------------
    sigs = signatures_for([(str(args.data / e.zip_name), e.member, e.sha256) for e in index],
                          cache=args.cache / "pixel_signatures.json", workers=args.workers)
    sig_list = list(sigs.values())
    pairs = near_duplicates(sig_list)
    # (row, col) -> row-subset images with a re-encoded copy (distinct bytes) in col
    reenc: dict[tuple[str, str], set[str]] = collections.defaultdict(set)
    for p in pairs:
        for x, y in ((p.a, p.b), (p.b, p.a)):
            for s in subsets_of[x]:
                for t in subsets_of[y]:
                    reenc[(s, t)].add(x)
    grid = threshold_table(sig_list)
    hams = sorted({h for h, _ in grid})
    corrs = sorted({c for _, c in grid})

    def any_copy(s: str) -> set[str]:
        return exact_elsewhere(s) | set().union(*(reenc[(s, o)] for o in subs if o != s))

    md += [
        "## Re-encoded copies: pixel evidence",
        ("Pairs of *different* files (distinct SHA-256) declared the same image when the "
        "perceptual-hash Hamming distance is ≤ 6 **and** the standardised-thumbnail "
        f"correlation is ≥ 0.95: **{len(pairs)} pair{'' if len(pairs) == 1 else 's'}**. "
        "Images in the row subset with such "
        "a copy in the column subset (the diagonal: within the subset):"),
        table(["", *(NAMES[s] for s in subs)],
              [[NAMES[r], *(len(reenc[(r, c)]) for c in subs)] for r in subs]),
        ("Pair counts across thresholds (rows: max Hamming distance; columns: min "
        "correlation), so the count does not rest on one cutoff:"),
        table(["Hamming ≤", *(f"corr ≥ {c}" for c in corrs)],
              [[h, *(grid[(h, c)] for c in corrs)] for h in hams]),
        (f"- Exact or re-encoded: **{len(any_copy('test'))} of {counts['test']} test images** "
        f"and **{len(any_copy('validation'))} of {counts['validation']} validation images** "
        "have a copy elsewhere in the release."),
    ]

    # --- inventory (check 1) -----------------------------------------------------
    per_c = collections.Counter(a["image_id"] for a in c_json["annotations"])
    per_c_img = [per_c.get(im["id"], 0) for im in c_json["images"]]
    per_b = collections.Counter(a["image_id"] for a in b_json["annotations"])
    diag = [r for r in rel.records if r.meta["source"].startswith("diagnosis/")]
    try:
        check_inventory([replace(r, teeth_present=frozenset(a.tooth_fdi for a in r.annotations),
                                 teeth_present_source=InventorySource.ANNOTATED)
                         for r in diag if r.annotations])
        guard = "**did not fire** (unexpected)"
    except ValueError:
        guard = "**fires**, as it should"
    inv = [r for r in rel.records if r.teeth_present is not None]
    reasons = collections.Counter(rel.inventory_conflicts.values())
    md += [
        "## Does (c) enumerate every tooth? (check 1)",
        (f"No. (c) boxes only diagnosed teeth: median {st.median(per_c_img)} boxes per image "
        f"(max {max(per_c_img)}; {per_c_img.count(0)} images with none), against a median "
        f"of {st.median(per_b.values())} in (b), which boxes every tooth. An inventory "
        f"rebuilt from (c)'s boxes is diseased-teeth-only, and `check_inventory` {guard}."),
        "Evaluation images (diagnosis train + validation) with a human inventory from a "
        f"byte-identical copy in (b): **{len(inv)}** (median "
        f"{st.median(len(r.teeth_present) for r in inv)} teeth; "
        f"{check_inventory(inv):.1%} of teeth carry no finding). Excluded from tooth-level "
        "metrics despite a (b) copy: "
        + ("; ".join(f"{n} because {why}" for why, n in reasons.items()) or "none") + ".",
    ]

    # --- test labels (check 3) ---------------------------------------------------
    by_region: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for labs in rel.test_labels.values():
        for lab in labs:
            by_region[f"test {lab.code}-{lab.word}"][region(lab.tooth_fdi % 10)] += 1
    for r in diag:
        for a in r.annotations:
            by_region[f"train {a.finding.value}"][region(a.tooth_fdi % 10)] += 1
    region_rows = [[k, sum(v.values()), *(f"{v[g] / sum(v.values()):.0%}"
                                          for g in ("incisor", "canine", "premolar", "molar"))]
                   for k, v in sorted(by_region.items())]
    by_sha = {r.meta["sha256"]: r for r in diag}
    shared_rows = []
    for h in shared_c_test:
        shared_rows.append([f"`{name_of[('diagnosis', h)]}` (train)", ", ".join(
            f"{a.tooth_fdi}: {a.finding.value}"
            for a in sorted(by_sha[h].annotations, key=lambda a: a.tooth_fdi))])
        shared_rows.append([f"`{name_of[('test', h)]}` (test)", ", ".join(
            f"{lab.tooth_fdi}: {lab.code}-{lab.word}"
            for lab in sorted(rel.test_labels[h], key=lambda x: x.tooth_fdi))])
    md += [
        "## Were the test labels released? (check 3)",
        (f"Yes ({len(rel.test_labels)} label files), but **not as the challenge's 4-class "
        "diagnosis ground truth**. They use an 8-code Turkish vocabulary that reads as "
        "treatment-oriented. The official evaluation script reads COCO ground truth with "
        "`category_id_1/2/3`, which is not in this release. Test codes against train "
        "diagnoses, by tooth region:"),
        table(["label", "n", "incisor", "canine", "premolar", "molar"], region_rows),
        ("`küretaj` (curettage) sits mostly on incisors, unlike deep caries, and fits "
        "periodontal treatment. `kanal` (root canal) and `çekim` (extraction) are treatment "
        "codes. The image(s) present in both train and test show the two schemes side by "
        "side:"),
        table(["image", "labels (FDI: label)"], shared_rows) if shared_rows else "(none)",
        ("**Consequence:** the released test set has no evaluation role in this project "
        "(see README). The depth-labelled evaluation set is diagnosis train + validation = "
        f"{counts['diagnosis'] + counts['validation']} images."),
    ]

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "report.md").write_text("\n\n".join(md) + "\n")
    print(f"wrote {args.out / 'report.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
